import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import {Inter} from "next/font/google";
import  Header  from "@/components/ui/Header";
import { ClerkProvider } from "@clerk/nextjs";



const inter=Inter({subsets:["latin"]});
export const metadata = {
  title: "Syncly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <ClerkProvider >
    <html lang="en">
      <body className={`${inter.className} dotted-background`}>
        <ThemeProvider attribute="class" defaultTheme="dark"  >
        
          <Header></Header>
        <main className="min-h-screen">{children}</main>
        <footer className="bg-gray-900 py-12">
          <div className="contianer mx-auto px-4 text-center text-gray-200">

         
         <p> made by hitesh roy</p>
         </div>

         </footer>

        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
